plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.4.20'
}
archivesBaseName = getArtifactId("common")

architectury {
    common(project.enabledPlatforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/oneironaut.accesswidener")
}

repositories {
    mavenCentral()
    maven {
        name = "Ladysnake Mods"
        url = 'https://maven.ladysnake.org/releases'
    }
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${project.fabricLoaderVersion}"
    modApi "dev.architectury:architectury:${project.architecturyVersion}"

    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.2' // for @Nonnull

    modCompileOnly "at.petra-k.paucal:paucal-common-$minecraftVersion:$paucalVersion"
    modCompileOnly "at.petra-k.hexcasting:hexcasting-fabric-$minecraftVersion:$hexcastingVersion"
    modCompileOnly "vazkii.patchouli:Patchouli-xplat:$minecraftVersion-$patchouliVersion"
    //modCompileOnly "maven.modrinth:hexal:${hexalVersion}"
    //modCompileOnly "maven.modrinth:geckolib:${geckolibVersion}"
    //modCompileOnly "maven.modrinth:hexgloop:${gloopVersion}"
    //modCompileOnly "maven.modrinth:wnboi:${wnboiVersion}"
    //modImplementation(annotationProcessor("com.github.llamalad7.mixinextras:mixinextras-common:${mixinExtrasVersion}"))
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-api:$cca_version"
    modImplementation("ram.talia.hexal:hexal-fabric-${minecraftVersion}:${hexalVersion}") { transitive false }
    modImplementation("ram.talia.moreiotas:moreiotas-fabric-${minecraftVersion}:${moreiotasVersion}") { transitive false }
    implementation group: "org.jblas", name: "jblas", version: "1.2.5"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = project.archivesBaseName
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
    }
}
